#!/bin/bash

echo "Enter marks for the following subjects:"
echo "1. Mathematics"
echo "2. Science"
echo "3. English"
echo "4. Social Science"
echo "5. Computer Science"

read -p "Mathematics: " math
read -p "Science: " science
read -p "English: " english
read -p "Social Science: " social
read -p "Computer Science: " computer

echo "---Mark List---"
echo "Mathematics: $math"
echo "Science: $science"
echo "English: $english"
echo "Social Science: $social"
echo "Computer Science: $computer"

total=$((math + science + english + social + computer))

percentage=$((total / 5))

if [ $percentage -ge 90 ]; then
  grade="A+"
elif [ $percentage -ge 80 ]; then
  grade="A"
elif [ $percentage -ge 70 ]; then
  grade="B+"
elif [ $percentage -ge 60 ]; then
  grade="B"
elif [ $percentage -ge 50 ]; then
  grade="C"
else
  grade="F"
fi

echo "Percentage: $percentage%"
echo "Grade: $grade"
