#!/bin/bash

echo "Enter first number: "
read num1
echo "Enter second number: "
read num2

echo "Enter choice:
1. Addition
2. Subtraction
3. Multiplication
4. Division"
read choice

case $choice in
  1) result=$(($num1 + $num2))
     echo "Addition of $num1 and $num2 is: $result";;
  2) result=$(($num1 - $num2))
     echo "Subtraction of $num1 and $num2 is: $result";;
  3) result=$(($num1 * $num2))
     echo "Multiplication of $num1 and $num2 is: $result";;
  4) result=$(($num1 / $num2))
     echo "Division of $num1 and $num2 is: $result";;
  *) echo "Invalid choice";;
esac
