#!/bin/bash

echo "Enter first number: "
read num1

echo "Enter second number: "
read num2

temp=$num1
num1=$num2
num2=$temp

echo "After exchanging, first number is $num1 and second number is $num2"
